#!/usr/bin/env bash
# =============================================================
#  Teach Nginx to trust Cloudflare's forwarded client IP.
#
#  With the Cloudflare proxy on, every request reaches the origin
#  from a Cloudflare address. Without this, access logs, the admin
#  panel's login throttling and any rate limiting all see one of a
#  handful of IPs instead of the visitor.
#
#  Run as root. Re-run occasionally: Cloudflare's ranges change.
#    bash cloudflare-realip.sh
# =============================================================
set -euo pipefail

OUT=/etc/nginx/conf.d/cloudflare-realip.conf
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

fetch() {
  curl -fsS --max-time 20 "$1" || { echo "Could not fetch $1" >&2; exit 1; }
}

{
  echo "# Generated by deploy/cloudflare-realip.sh on $(date -u +%F)"
  echo "# Cloudflare edge ranges — do not edit by hand."
  fetch https://www.cloudflare.com/ips-v4 | while read -r cidr; do
    [[ -n "$cidr" ]] && echo "set_real_ip_from $cidr;"
  done
  fetch https://www.cloudflare.com/ips-v6 | while read -r cidr; do
    [[ -n "$cidr" ]] && echo "set_real_ip_from $cidr;"
  done
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
} > "$TMP"

# Only replace the live file if the result is valid.
cp "$TMP" "$OUT"
if nginx -t; then
  systemctl reload nginx
  echo "Nginx now trusts Cloudflare for the client IP ($(grep -c set_real_ip_from "$OUT") ranges)."
else
  rm -f "$OUT"
  nginx -t
  echo "! Invalid config — removed $OUT and left Nginx as it was." >&2
  exit 1
fi
