/* =============================================================
   Turns the stored content into the live static site.

     content.json -> assets/js/overrides.js -> prerender -> web root

   The browser and the prerenderer both read overrides.js, so an
   edit shows up identically with JavaScript on or off.
   ============================================================= */
'use strict';

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const store = require('./store');

const ROOT = store.defaults.ROOT;
const OVERRIDES = path.join(ROOT, 'assets/js/overrides.js');

function writeOverrides() {
  const c = store.rawContent();
  const resolved = store.resolved();

  const lines = [
    '/* Generated by the admin panel — do not edit by hand.',
    '   Regenerate with: node server/build.js */',
    '(function (w) {',
    '  w.SITE = ' + JSON.stringify(resolved.site, null, 2).replace(/\n/g, '\n  ') + ';'
  ];

  if (c.products) {
    lines.push('  w.PRODUCTS = ' + JSON.stringify(c.products, null, 2).replace(/\n/g, '\n  ') + ';');
  }
  if (c.trustLogos) {
    lines.push('  w.TRUST_LOGOS = ' + JSON.stringify(c.trustLogos) + ';');
  }
  if (c.i18n && Object.keys(c.i18n).length) {
    for (const [lang, entries] of Object.entries(c.i18n)) {
      if (!entries || !Object.keys(entries).length) continue;
      lines.push('  if (w.I18N && w.I18N.' + lang + ') Object.assign(w.I18N.' + lang + ', ' +
        JSON.stringify(entries, null, 2).replace(/\n/g, '\n  ') + ');');
    }
  }

  lines.push('})(typeof window !== "undefined" ? window : global);', '');
  fs.writeFileSync(OVERRIDES, lines.join('\n'));
}

function prerender(siteUrl) {
  return execFileSync('node', [path.join(ROOT, 'tools/prerender.js'), siteUrl], {
    cwd: ROOT, encoding: 'utf8'
  });
}

/* Builds into a fresh directory and swaps it in, so a failure can
   never leave the live site half-written. */
function publish(webRoot) {
  const staging = webRoot + '.new';
  fs.rmSync(staging, { recursive: true, force: true });
  fs.mkdirSync(staging, { recursive: true });

  const excludes = ['.git', '.github', 'tools', 'deploy', 'server', 'README.md', '.gitignore'];
  execFileSync('bash', ['-c',
    'tar -c ' + excludes.map((e) => "--exclude='./" + e + "'").join(' ') +
    ' . | tar -x -C ' + JSON.stringify(staging)
  ], { cwd: ROOT });

  const old = webRoot + '.old';
  fs.rmSync(old, { recursive: true, force: true });

  try {
    if (fs.existsSync(webRoot)) fs.renameSync(webRoot, old);
    fs.renameSync(staging, webRoot);
    fs.rmSync(old, { recursive: true, force: true });
  } catch (err) {
    // The web root can be a mount point (systemd ReadWritePaths does
    // this), and a mount point cannot be renamed. Swap the contents
    // instead: still only local renames, so it stays quick.
    if (err.code !== 'EBUSY' && err.code !== 'EXDEV') throw err;
    if (fs.existsSync(old) && !fs.existsSync(webRoot)) fs.renameSync(old, webRoot);

    // Staging may sit on a different filesystem from the mount, so
    // copy rather than rename. The site is small; this is quick.
    for (const entry of fs.readdirSync(webRoot)) {
      fs.rmSync(path.join(webRoot, entry), { recursive: true, force: true });
    }
    for (const entry of fs.readdirSync(staging)) {
      fs.cpSync(path.join(staging, entry), path.join(webRoot, entry), { recursive: true });
    }
    fs.rmSync(staging, { recursive: true, force: true });
  }
}

function rebuild(opts) {
  const siteUrl = (opts && opts.siteUrl) || process.env.SITE_URL || 'http://localhost';
  const webRoot = (opts && opts.webRoot) || process.env.WEB_ROOT || '/var/www/myappshop';

  writeOverrides();
  const log = prerender(siteUrl);
  publish(webRoot);
  return log;
}

module.exports = { rebuild, writeOverrides, publish };

if (require.main === module) {
  const out = rebuild({
    siteUrl: process.argv[2] || process.env.SITE_URL,
    webRoot: process.argv[3] || process.env.WEB_ROOT
  });
  process.stdout.write(out);
  console.log('published');
}
